service: facturacion-sls

custom:
  serviceAndStage: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action: '*'
      Resource: '*'

  environment:
    dynamoDBPrefix: ${self:custom.serviceAndStage}-

package:
  exclude:
    - ./**
  include:
    - src/**
    - node_modules/**

functions:
  CrearVenta:
    handler: src/Venta.crear
    events:
      - http:
          path: ventas
          method: POST

resources:
  - ${file(resources/dynamodb.yml)}
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
